# -*- coding: utf-8 -*-

{'name': 'Zencore Fakir CRM Portal',
 'version': '20.0.1.12.5',
 'summary': 'CRM Portal',
 'description': '\nCRM Portal\n    ',
 'author': 'Saiful Islam Shawon',
 'category': 'CRM',
 'license': 'LGPL-3',
 'depends': ['base',
             'website',
             'portal',
             'crm',
             'utm',
             'account',
             'base_geolocalize',
             'website_crm_partner_assign'],
 'data': ['security/security.xml',
          'security/ir.access.csv',
          'views/crm_template.xml',
          'views/backend_send_mail_views.xml',
          'views/crm_lead_views.xml',
          'views/portal_crm_template.xml',
          'views/website_menu.xml',
          'views/fakir_reference_crm.xml'],
 'assets': {'web.assets_frontend': ['zencore_fakir_crm_portal/static/src/scss/fakir_reference_crm.scss',
                                    'zencore_fakir_crm_portal/static/src/interactions/fakir_reference_crm.js',
                                    'zencore_fakir_crm_portal/static/src/scss/crm.scss',
                                    'zencore_fakir_crm_portal/static/src/js/crm.js',
                                    'zencore_fakir_crm_portal/static/src/scss/portal_crm.scss',
                                    'zencore_fakir_crm_portal/static/src/js/portal_crm.js',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_crm_v20.js',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_detail_standard.scss',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_details_live.js',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_detail_products_inline.js',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_detail_readability.scss',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_detail_readability.js',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_smart_counts.js',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_extra_partner_readability.scss',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_extra_partner_search.js',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_assignment_toast.js',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_assignment_toast.scss',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_activity_modal_click_fix.js',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_v20_list_columns.js',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_v20_list_fixes.scss',
                                    'zencore_fakir_crm_portal/static/src/scss/fakir_chatter_types.scss',
                                    'zencore_fakir_crm_portal/static/src/js/fakir_mail_sending_state.js']},
 'installable': True,
 'application': True,
 'auto_install': False}
