{
    "name": "CS",
    "summary": "Requisition-based multi-vendor RFQ comparison and product-wise vendor selection",
    "version": "20.0.1.0.17",
    "category": "Purchases",
    "author": "Mehedi Hasan",
    "website": "https://www.zencoreltd.com",
    "license": "LGPL-3",
    "depends": ["mail", "purchase", "approvals"],
    "data": [
        "security/security.xml",
        "security/ir.access.csv",
        "data/sequence.xml",
        "reports/comparison_sheet_report.xml",
        "reports/comparison_sheet_template.xml",
        "views/rfq_comparison_views.xml",
        "views/purchase_requisition_views.xml",
        "views/vendor_rfq_views.xml",
        "views/approval_request_views.xml",
        "views/purchase_order_views.xml",
        "wizard/rfq_create_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
